# **Introducción a PyTorch**

In [1]:
import torch

In [2]:
#Tensor de 1 dimensión

tensor_una_d= torch.LongTensor([0])
print(f'La forma de  {tensor_una_d} es {tensor_una_d.shape} y su dimensión es {tensor_una_d.dim()}' )

La forma de  tensor([0]) es torch.Size([1]) y su dimensión es 1


In [3]:
#Otro tensor de 1 dimensión

tensor_una_d= torch.LongTensor([0, 1, 2])
print(f'La forma de  {tensor_una_d} es {tensor_una_d.shape} y su dimensión es {tensor_una_d.dim()}' )

La forma de  tensor([0, 1, 2]) es torch.Size([3]) y su dimensión es 1


In [4]:
#Tensor de 2 dimensiones

tensor_dos_d= torch.LongTensor([[0, 1, 2], [3, 4, 5]])
print (tensor_dos_d)
print(f'La forma de  {tensor_dos_d} es {tensor_dos_d.shape} y su dimensión es {tensor_dos_d.dim()}' )

tensor([[0, 1, 2],
        [3, 4, 5]])
La forma de  tensor([[0, 1, 2],
        [3, 4, 5]]) es torch.Size([2, 3]) y su dimensión es 2


In [5]:
#Otro tensor de 2 dimensiones

tensor_dos_d= torch.LongTensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print (tensor_dos_d)
print(f'La forma de  {tensor_dos_d} es {tensor_dos_d.shape} y su dimensión es {tensor_dos_d.dim()}' )

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
La forma de  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) es torch.Size([3, 3]) y su dimensión es 2


In [7]:
# Tensor de 3 dimensiones
tensor_tres_d = torch.LongTensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
                                  [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
                                  [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
print(tensor_tres_d)
print(f'La forma de {tensor_tres_d} es {tensor_tres_d.shape} y su dimensión es {tensor_tres_d.dim()}')


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
La forma de tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]) es torch.Size([3, 3, 3]) y su dimensión es 3


In [10]:
tensor_tres_d * 2

tensor([[[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]],

        [[18, 20, 22],
         [24, 26, 28],
         [30, 32, 34]],

        [[36, 38, 40],
         [42, 44, 46],
         [48, 50, 52]]])

In [11]:
tensor_tres_d * .5

tensor([[[ 0.0000,  0.5000,  1.0000],
         [ 1.5000,  2.0000,  2.5000],
         [ 3.0000,  3.5000,  4.0000]],

        [[ 4.5000,  5.0000,  5.5000],
         [ 6.0000,  6.5000,  7.0000],
         [ 7.5000,  8.0000,  8.5000]],

        [[ 9.0000,  9.5000, 10.0000],
         [10.5000, 11.0000, 11.5000],
         [12.0000, 12.5000, 13.0000]]])

In [12]:
tensor_tres_d - 2

tensor([[[-2, -1,  0],
         [ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])

In [13]:
tensor_tres_d + 2

tensor([[[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[20, 21, 22],
         [23, 24, 25],
         [26, 27, 28]]])

In [9]:
tensor_tres_d ** 2

tensor([[[  0,   1,   4],
         [  9,  16,  25],
         [ 36,  49,  64]],

        [[ 81, 100, 121],
         [144, 169, 196],
         [225, 256, 289]],

        [[324, 361, 400],
         [441, 484, 529],
         [576, 625, 676]]])

In [14]:
sum(tensor_tres_d)

tensor([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]])

In [28]:
sum(sum(tensor_tres_d))

tensor([108, 117, 126])